### ISSUE TITLE
Not able to store data above 2GB!

### ISSUE THREAD

**Issue by sherry-ummen** [Softmotions/ejdb-csharp#6]
Hi,

Tried to stores some quite large data. and I reached to a point of 2Gb of file sixe after that the process just hung. When I stop it and start again then i get StackOverFlowexception from EJB.cs 

internal static bool _ejdbopen(IntPtr db, string path, int mode) {
            IntPtr pptr = Native.NativeUtf8FromString(path); //UnixMarshal.StringToHeap(path, Encoding.UTF8);
            try {
                return _ejdbopen(db, pptr, mode);
            } finally {
                Marshal.FreeHGlobal(pptr); //UnixMarshal.FreeHeap(pptr);
            }
        }

At this particular line: return _ejdbopen(db, pptr, mode);

**Comment by adamansky** [comment]
Fixed in https://github.com/Softmotions/ejdb/issues/149
